### ISSUE TITLE
Error When Utilizing the Exporter on RC with High User Count

### ISSUE THREAD

**Issue by phoenixfxc** [frdmn/rocketchat-export-userlist#4]
I have about 140,000 users, and I need to export them all. After running the exporter, this is what I get:

error:  { RequestError: Error, too many requests. Please slow down. You must wait 55 seconds before trying this endpoint again. [error-too-many-requests]
    at Request.clientRequest [as _callback] (/root/userexport/rocketchat-export-userlist/node_modules/rocketchat/lib/net.js:146:38)
    at Request.self.callback (/root/userexport/rocketchat-export-userlist/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/root/userexport/rocketchat-export-userlist/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/root/userexport/rocketchat-export-userlist/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'RequestError', statusCode: 429 }

**Comment by frdmn** [comment]
@phoenixfxc Can you check your rate limiter settings in the Admin UI → Rate Limiter → API Rate Limiter and adjust or disable it temporary while using the exporter?

**Comment by phoenixfxc** [comment]
Okay so it almost worked. This is a pretty beefy linode server, and somehow it still managed to run out of resources I guess? Is there a way to batch this?

Added 100 users from this request (29600 so far)...
Added 100 users from this request (29700 so far)...
Added 100 users from this request (29800 so far)...
Added 100 users from this request (29900 so far)...
Added 100 users from this request (30000 so far)...
Added 100 users from this request (30100 so far)...
Added 100 users from this request (30200 so far)...
error:  { RequestError: Executor error during find command :: caused by :: errmsg: "Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."
    at Request.clientRequest [as _callback] (/root/userexport/rocketchat-export-userlist/node_modules/rocketchat/lib/net.js:146:38)
    at Request.self.callback (/root/userexport/rocketchat-export-userlist/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/root/userexport/rocketchat-export-userlist/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/root/userexport/rocketchat-export-userlist/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'RequestError', statusCode: 400 }
root@Rocketchat-server-2:~/userexport/rocketchat-export-userlist# packet_write_wait: Connection to 165.227.10.120 port 22: Broken pipe

**Comment by phoenixfxc** [comment]
Figured out I can do this: db.adminCommand({setParameter: 1, internalQueryExecMaxBlockingSortBytes: 209715200})

Now it's climbed past 75,000. Sounds like if it stops again it would just need another bump
